### ISSUE TITLE
Unable to change color of existing note!

### ISSUE THREAD

**Issue by shivamchourasia4** [akshatmittal61/planner#13]
Right now the color of pre existing note cannot be changed! 
I would like to work on this. Can you assign this to me as part of hacktoberfest?

**Comment by akshatmittal61** [comment]
Yes sure, fork the repo, make the necessary changes, and raise a PR. I will merge your PR after reviewing it.

**Comment by shivamchourasia4** [comment]
Also the label should be "hacktoberfest-accepted". Can you please update it!

**Comment by shivamchourasia4** [comment]
Also while merging my PR, do add the **hacktoberfest-accepted** label to it!

**Comment by shivamchourasia4** [comment]
@akshatmittal61 can you review my PR once, please?

**Comment by akshatmittal61** [comment]
Your PR has been reviewed and merged. Thanks for your contribution. :grinning:
