### ISSUE TITLE
Cannot access settings in mobile view

### ISSUE THREAD

**Issue by Va1nsh14** [akshatmittal61/planner#16]
The settings page has a menu to change the accent color of application.
But in mobile view, the user cannot access all the colors and cannot scroll to get their either.

**Expected behavior**
The user should either be able to scroll to get to the right color or the color palette should be wrapped for accessibility.

**Screenshots**

![planner netlify app_settings(Pixel 5)](https://user-images.githubusercontent.com/62149456/193504964-21a1126f-5568-4bb6-b1b3-2e2fcb3d1786.png)

**Comment by grraghav120** [comment]
Please assign it to me. I want to work on this issue. I get it wrong missing ..

**Comment by akshatmittal61** [comment]
> Hii @akshatmittal61 Please assign it to me. I want to work on this issue. I get it what's missing ..

OK, @grraghav120, you may work on this now, I will review your work after you have raised a PR for the same.

**Comment by akshatmittal61** [comment]
This issue has been resolved in [`48605e6`](https://github.com/akshatmittal61/planner/commit/48605e646496f9fd70ae3faf22f8673458a253fa)
