### ISSUE TITLE
Adding Follow buttons/Sharing buttons in Planner

### ISSUE THREAD

**Issue by grraghav120** [akshatmittal61/planner#18]
**Is your feature request related to a problem? Please describe.**
We can add a new features like Follow buttons or Sharing buttons.

**Describe the solution you'd like**
buttons like 
![image](https://user-images.githubusercontent.com/96789493/193524720-67a6203e-f1e0-45ad-afe4-fe5dcbfb8e77.png)

Assign me this issue if you also like it

**Comment by grraghav120** [comment]
Assign me this issue if you also like it @akshatmittal61

**Comment by akshatmittal61** [comment]
To which component do you want to add these follow/share buttons?
Can you elaborate on it, please?
