### ISSUE TITLE
Fixing typo and enhancing sentences within README file

### ISSUE THREAD

**Issue by supminn** [akshatmittal61/planner#20]
**Describe the bug**
I came across a few sentences which could be rephrased for better understanding. I have also corrected a few typos present in the README.md file.

**Additional context**
Updating these changes as a part of `Low code` or `No code` changes for the hacktoberfest 2022. Appreciate it if you could add the `hacktoberfest` tag to the issue and PR.

**Comment by akshatmittal61** [comment]
Your PR has been merged. Thank you for your contribution. :grinning:
