### ISSUE TITLE
Cannot access calendar controls in all small screens

### ISSUE THREAD

**Issue by Anshi25** [akshatmittal61/planner#23]
**Describe the bug**
The buttons in Calendar header are inaccessible in small screens.

**Expected behavior**
User should be able to click all the buttons in the small screens.

**Screenshots**
![WhatsApp Image 2022-10-05 at 11 56 21](https://user-images.githubusercontent.com/85192826/193995047-b19f638f-acbb-4469-b6b6-21dc003a1690.jpeg)

**Comment by Anshi25** [comment]
I would like to work on this issue, can you assign it to me? Thanks

**Comment by akshatmittal61** [comment]
Yes sure, raise a PR after making required changes and we will review and merge those changes afterwards.

**Comment by akshatmittal61** [comment]
This issue has been solved in #25
