### ISSUE TITLE
Missing .env file? 

### ISSUE THREAD

**Issue by jing-yu-lim** [akshatmittal61/planner#30]
**Describe the bug**

" The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string."

Hi. It appears that the server requires some variables defined in the .env file e.g. dbURI as argument to the function mongoose.connect(dbUri). I am new to React so I would like to kindly request for your configurations for these variables.

Please kindly share the .env file as it would be really helpful to learn which port should match the port the frontend is served on. Thank you!

**To Reproduce**
Follow the running steps in Readme

**Comment by akshatmittal61** [comment]
The `.env` file is an environment configuration variables file and thus cannot be disclosed publicly. However, I have connected a [`.env.example`](https://github.com/akshatmittal61/planner/blob/master/.env.example) file now to provide guidelines to build your environment configurations.

Solved in [`eb12e1a`](https://github.com/akshatmittal61/planner/commit/eb12e1aeafc72444bf9a77290bc9faa033d91de3)
