### ISSUE TITLE
verify token bug

### ISSUE THREAD

**Issue by Anshi25** [akshatmittal61/planner#6]
On every re render the user state fetches data from local storage  instead of remote servers.  This has created a bug whenever a user updates his profile from a remote device, the former device does not synchronise with the changes.
Please resolve this.

**Comment by akshatmittal61** [comment]
Hello!
Thanks for raising this.
It has been fixed in [`f0496ca`](https://github.com/akshatmittal61/planner/commit/f0496ca915b79e6fa7b05e17d229e795b34fb42a)
